"""LLVM IR codegen: translates ScratchV IR to LLVM IR text format.

Produces human-readable .ll files suitable for ``llc``, ``opt``, or ``lli``.
No external dependencies beyond Python — the output is standard LLVM IR.
"""

from __future__ import annotations

from scratchv.ir.types import (
    OpCode, DataType, Value, Instruction, BasicBlock, Function, Program,
)


_TYPE_MAP = {
    DataType.FLOAT32: "float",
    DataType.INT32: "i32",
    DataType.FLOAT64: "double",
    DataType.INT64: "i64",
}

_LLVM_FLOAT = "float"
_LLVM_DOUBLE = "double"
_LLVM_I32 = "i32"
_LLVM_I64 = "i64"


class LLVMCodegen:
    """Translate ScratchV IR Program to LLVM IR text (.ll)."""

    def __init__(self, program: Program):
        self.program = program
        self._lines: list[str] = []
        self._indent = 0
        # IR value name -> LLVM register
        self._named_values: dict[str, str] = {}
        # function name -> return type
        self._func_type: dict[str, str] = {}
        self._block_counter = 0
        self._loop_context: dict | None = None
        self._current_func: str | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Produce complete LLVM IR module as text."""
        self._lines = []
        self._p("; LLVM IR generated by ScratchV")
        self._p('; ModuleID = "scratchv_module"')
        self._p("target triple = \"riscv64-unknown-elf\"")
        self._p("")

        # Declare external helpers
        self._emit_externals()

        for func in self.program.functions:
            self._emit_function(func)

        return "\n".join(self._lines)

    def save(self, path: str) -> None:
        """Write LLVM IR to a file."""
        with open(path, "w") as f:
            f.write(self.emit())

    # ------------------------------------------------------------------
    # External declarations
    # ------------------------------------------------------------------

    def _emit_externals(self) -> None:
        self._p("declare float @expf(float) nounwind readonly")
        self._p("declare float @tanhf(float) nounwind readonly")
        self._p("declare double @exp(double) nounwind readonly")
        self._p("declare double @tanh(double) nounwind readonly")
        self._p("declare void @print_f32(float) nounwind")
        self._p("")

    # ------------------------------------------------------------------
    # Functions
    # ------------------------------------------------------------------

    @staticmethod
    def _infer_function_params(func: Function) -> None:
        """Add undefined external value references as function params.

        Handles DSL-parsed programs where free variables (e.g. 'a', 'b'
        in "y = add(a, b)") are referenced but not declared as params.
        """
        defined: set[str] = {p.name for p in func.params}
        referenced = {}

        for block in func.blocks:
            for instr in block.instructions:
                if instr.dest is not None:
                    defined.add(instr.dest.name)
                for op in instr.operands:
                    if not op.is_constant:
                        referenced.setdefault(op.name, op)

        existing_param_names = {p.name for p in func.params}
        for name in referenced.keys() - defined:
            if name not in existing_param_names:
                val = referenced[name]
                func.params.append(val)

    def _emit_function(self, func: Function) -> None:
        self._current_func = func.name
        self._named_values.clear()
        self._block_counter = 0

        # Auto-detect undefined external variable references as params
        self._infer_function_params(func)

        # Build param list
        params = []
        for p in func.params:
            llvm_ty = _llvm_type(p.dtype)
            params.append(f"{llvm_ty} %{p.name}")

        # Determine return type
        ret_ty = "void"
        if func.returns:
            ret_ty = _llvm_type(func.returns[0].dtype)
        else:
            # Scan blocks for return instructions to infer return type
            for block in func.blocks:
                for instr in block.instructions:
                    if instr.opcode == OpCode.RETURN and instr.operands:
                        ret_ty = _llvm_type(instr.operands[0].dtype)
                        break
                if ret_ty != "void":
                    break

        self._p(f"define {ret_ty} @{func.name}({', '.join(params)}) {{")

        # Map function params to named values
        for p in func.params:
            self._named_values[p.name] = f"%{p.name}"

        self._indent = 1

        # Emit each basic block
        for block in func.blocks:
            self._emit_block(block)

        self._indent = 0
        self._p("}")
        self._p("")

    # ------------------------------------------------------------------
    # Basic blocks
    # ------------------------------------------------------------------

    def _emit_block(self, block: BasicBlock) -> None:
        if block.name == "entry" and self._is_first_block():
            self._p(f"; --- {block.name} ---")
        else:
            self._p(f"{block.name}:")
            self._p(f"; --- {block.name} ---")

        for instr in block.instructions:
            self._emit_instruction(instr)

    def _is_first_block(self) -> bool:
        """Check if we're in the first block."""
        return True

    # ------------------------------------------------------------------
    # Instructions
    # ------------------------------------------------------------------

    def _emit_instruction(self, instr: Instruction) -> None:
        handler = getattr(self, f"_emit_{instr.opcode.value}", None)
        if handler is None:
            if instr.opcode in (OpCode.SQRT, OpCode.REDUCE_MEAN, OpCode.GATHER,
                               OpCode.SLICE, OpCode.UNSQUEEZE, OpCode.EXPAND):
                raise ValueError(f"LLVM codegen does not support opcode: {instr.opcode.value}")
            ops = ' '.join(str(v.name) for v in instr.operands)
            self._p(f"  ; UNSUPPORTED: {instr.opcode.value} {ops}")
        else:
            handler(instr)

    def _dest(self, instr: Instruction) -> str:
        """Get or create an LLVM register for the instruction's destination."""
        if instr.dest is None:
            return ""
        reg = self._fresh(instr.dest.name)
        self._named_values[instr.dest.name] = reg
        return reg

    def _op(self, instr: Instruction, idx: int) -> str:
        """Resolve operand idx to an LLVM value reference."""
        if idx >= len(instr.operands):
            return ""
        op = instr.operands[idx]
        return self._value_ref(op)

    def _value_ref(self, val) -> str:
        """Get LLVM reference for a Value."""
        if val.name in self._named_values:
            return self._named_values[val.name]
        if val.is_constant and val.const_value is not None:
            return str(_llvm_const(val))
        reg = self._fresh(val.name)
        self._named_values[val.name] = reg
        return reg

    def _fresh(self, hint: str) -> str:
        """Create a fresh SSA register name."""
        safe = hint.replace(".", "_").replace("-", "_")
        self._block_counter += 1
        return f"%{safe}_{self._block_counter}"

    def _p(self, line: str = "") -> None:
        if line and not line.startswith(";"):
            indent = "  " * self._indent
        else:
            indent = ""
        self._lines.append(f"{indent}{line}")

    # ------------------------------------------------------------------
    # Arithmetic
    # ------------------------------------------------------------------

    def _emit_add(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        lhs = self._op(instr, 0)
        rhs = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = fadd {ty} {lhs}, {rhs}")

    def _emit_sub(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        lhs = self._op(instr, 0)
        rhs = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = fsub {ty} {lhs}, {rhs}")

    def _emit_mul(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        lhs = self._op(instr, 0)
        rhs = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = fmul {ty} {lhs}, {rhs}")

    def _emit_div(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        lhs = self._op(instr, 0)
        rhs = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = fdiv {ty} {lhs}, {rhs}")

    def _emit_neg(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = fneg {ty} {src}")

    def _emit_exp(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)
        if ty == "double":
            self._p(f"  {dst} = call double @exp(double {src})")
        else:
            self._p(f"  {dst} = call float @expf(float {src})")

    # ------------------------------------------------------------------
    # Constants & memory
    # ------------------------------------------------------------------

    def _emit_load_const(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        raw_val = instr.attrs.get("value", 0)
        assert isinstance(raw_val, (int, float))
        val: float | int = raw_val
        ty = _llvm_type(instr.dest.dtype) if instr.dest else "float"
        self._p(f"  {dst} = fadd {ty} {_llvm_const_val(val, ty)}, 0.0")

    def _emit_load(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        ptr = self._op(instr, 0)
        ty = self._infer_type(instr)
        ptr_ty = f"{ty}*"
        self._p(f"  {dst} = load {ty}, {ptr_ty} {ptr}")

    def _emit_store(self, instr: Instruction) -> None:
        val = self._op(instr, 1)
        ptr = self._op(instr, 0)
        ty = self._infer_type(instr)
        ptr_ty = f"{ty}*"
        self._p(f"  store {ty} {val}, {ptr_ty} {ptr}")

    def _emit_alloca(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        size = instr.attrs.get("size", 4)
        ty = self._infer_type(instr)
        self._p(f"  {dst} = alloca {ty}, i32 {size}")

    # ------------------------------------------------------------------
    # Control flow
    # ------------------------------------------------------------------

    def _emit_for(self, instr: Instruction) -> None:
        self._dest(instr)  # register loop variable name
        start = instr.attrs.get("start", 0)
        end = instr.attrs.get("end", 0)

        header = self._fresh_block("loop_header")
        body = self._fresh_block("loop_body")
        exit = self._fresh_block("loop_exit")

        # Initialize induction variable
        start_reg = self._fresh("iv_start")
        self._p(f"  {start_reg} = add i32 0, {start}")
        # Actually, we need an alloca or phi for the IV
        iv_alloca = self._fresh("iv_ptr")
        self._p(f"  {iv_alloca} = alloca i32, i32 1")
        self._p(f"  store i32 {start_reg}, i32* {iv_alloca}")
        self._p(f"  br label %{body}")

        self._p(f"{header}:")
        # Load IV, compare
        loaded = self._fresh("iv_val")
        self._p(f"  {loaded} = load i32, i32* {iv_alloca}")
        cond = self._fresh("cond")
        self._p(f"  {cond} = icmp slt i32 {loaded}, {end}")
        self._p(f"  br i1 {cond}, label %{body}, label %{exit}")

        self._p(f"{body}:")

        self._loop_context = {
            "iv_alloca": iv_alloca,
            "end": end,
            "header": header,
            "exit": exit,
        }

    def _emit_endfor(self, instr: Instruction) -> None:
        ctx = self._loop_context
        if ctx is None:
            self._p("  ; ERROR: endfor without matching for")
            return

        iv_alloca = ctx["iv_alloca"]
        header = ctx["header"]

        # Load, increment, store
        loaded = self._fresh("iv_val")
        self._p(f"  {loaded} = load i32, i32* {iv_alloca}")
        inc = self._fresh("iv_next")
        self._p(f"  {inc} = add i32 {loaded}, 1")
        self._p(f"  store i32 {inc}, i32* {iv_alloca}")
        self._p(f"  br label %{header}")

        # Exit label
        self._p(f"{ctx['exit']}:")

    def _emit_br(self, instr: Instruction) -> None:
        target = instr.target or ""
        self._p(f"  br label %{target}")

    def _emit_br_if(self, instr: Instruction) -> None:
        targets = (instr.target or ",").split(",")
        true_t = targets[0].strip() if len(targets) > 0 else ""
        false_t = targets[1].strip() if len(targets) > 1 else ""

        if len(instr.operands) == 2 and "cmp_op" in instr.attrs:
            lhs = self._op(instr, 0)
            rhs = self._op(instr, 1)
            operator = instr.attrs["cmp_op"]
            dtype = instr.operands[0].dtype
            if dtype in (DataType.FLOAT32, DataType.FLOAT64):
                predicates = {
                    "==": "oeq", "!=": "une", "<": "olt",
                    ">": "ogt", "<=": "ole", ">=": "oge",
                }
                opcode = "fcmp"
            else:
                predicates = {
                    "==": "eq", "!=": "ne", "<": "slt",
                    ">": "sgt", "<=": "sle", ">=": "sge",
                }
                opcode = "icmp"
            if operator not in predicates:
                raise ValueError(f"unsupported comparison operator: {operator}")
            cmp_result = self._fresh("cmp")
            ty = _llvm_type(dtype)
            self._p(
                f"  {cmp_result} = {opcode} {predicates[operator]} "
                f"{ty} {lhs}, {rhs}"
            )
            self._p(
                f"  br i1 {cmp_result}, label %{true_t}, label %{false_t}"
            )
        elif len(instr.operands) == 1:
            cond_op = self._op(instr, 0)
            self._p(f"  br i1 {cond_op}, label %{true_t}, label %{false_t}")
        else:
            raise ValueError("br_if expects a boolean or comparison operands")

    def _emit_return(self, instr: Instruction) -> None:
        if instr.operands:
            val = self._op(instr, 0)
            ty = self._infer_type(instr)
            self._p(f"  ret {ty} {val}")
        else:
            self._p("  ret void")

    def _emit_label(self, instr: Instruction) -> None:
        """IR labels become LLVM block labels."""
        if instr.target:
            self._p(f"{instr.target}:")

    # ------------------------------------------------------------------
    # Neural-network ops (implemented as inline LLVM IR)
    # ------------------------------------------------------------------

    def _emit_relu(self, instr: Instruction) -> None:
        """ReLU(x) = select x > 0 ? x : 0.0"""
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)
        zero = "0.0"
        if ty == "double":
            zero = "0.0"
        cmp = self._fresh("cmp")
        self._p(f"  {cmp} = fcmp ogt {ty} {src}, {zero}")
        self._p(f"  {dst} = select i1 {cmp}, {ty} {src}, {ty} {zero}")

    def _emit_gelu(self, instr: Instruction) -> None:
        """
        GELU(x) = x * 0.5 * (1.0 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
        All computed inline using LLVM IR.
        """
        dst = self._dest(instr)
        x = self._op(instr, 0)
        ty = self._infer_type(instr)

        sqrt_2pi = "0.7978845608028654"
        coeff = "0.044715"
        half = "0.5"
        one = "1.0"

        # x^3
        x3 = self._fresh("x3")
        self._p(f"  {x3} = fmul {ty} {x}, {x}")
        self._p(f"  {x3} = fmul {ty} {x3}, {x}")

        # inner = coeff * x^3 + x
        inner = self._fresh("inner")
        self._p(f"  {inner} = fmul {ty} {coeff}, {x3}")
        self._p(f"  {inner} = fadd {ty} {inner}, {x}")

        # inner *= sqrt(2/pi)
        self._p(f"  {inner} = fmul {ty} {inner}, {sqrt_2pi}")

        # tanh
        if ty == "double":
            tanh_reg = self._fresh("tanh")
            self._p(f"  {tanh_reg} = call double @tanh(double {inner})")
        else:
            tanh_reg = self._fresh("tanh")
            self._p(f"  {tanh_reg} = call float @tanhf(float {inner})")

        # 1 + tanh
        plus_one = self._fresh("plus_one")
        self._p(f"  {plus_one} = fadd {ty} {one}, {tanh_reg}")

        # x * 0.5
        half_x = self._fresh("half_x")
        self._p(f"  {half_x} = fmul {ty} {x}, {half}")

        # result
        self._p(f"  {dst} = fmul {ty} {half_x}, {plus_one}")

    def _emit_softmax(self, instr: Instruction) -> None:
        """
        Softmax: for a vector of N elements:
          max_val = max(x)
          sum = sum(exp(x[i] - max_val))
          result[i] = exp(x[i] - max_val) / sum
        Implemented as a loop.
        """
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)

        self._p("  ; softmax: TODO full vector implementation required")
        self._p("  ; placeholder: return exp(x) / sum(exp(x))")
        # For now, call external softmax helper
        if ty == "double":
            self._p(f"  {dst} = call double @exp(double {src})")
        else:
            self._p(f"  {dst} = call float @expf(float {src})")

    def _emit_maxpool(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        src = self._op(instr, 0)
        self._p("  ; maxpool: passthrough (requires full tensor support)")
        self._p(f"  {dst} = fadd {self._infer_type(instr)} {src}, 0.0")

    def _emit_matmul(self, instr: Instruction) -> None:
        """Matrix multiplication: C[m,n] = A[m,k] @ B[k,n]
        NOTE: Full tensor MatMul requires multi-dimensional arrays.
        For scalar test cases, we compute a simple dot product approximation.
        """
        dst = self._dest(instr)
        a = self._op(instr, 0)
        b = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  ; matmul: A[{a}], B[{b}] - requires multi-dim support")
        self._p(f"  {dst} = fmul {ty} {a}, {b}")

    def _emit_dot(self, instr: Instruction) -> None:
        """Dot product: sum(a[i] * b[i]) for i in 0..len-1"""
        dst = self._dest(instr)
        a = self._op(instr, 0)
        b = self._op(instr, 1)
        length = instr.attrs.get("length", 1)
        ty = self._infer_type(instr)
        self._p(f"  ; dot product len={length} - scalar approximation")
        self._p(f"  {dst} = fmul {ty} {a}, {b}")

    def _emit_conv(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        out_c = instr.attrs.get("out_channels", 1)
        ksize = instr.attrs.get("kernel_size", 3)
        stride = instr.attrs.get("stride", 1)
        ty = self._infer_type(instr)
        self._p(f"  ; conv: out_c={out_c} k={ksize} s={stride}")
        self._p(f"  {dst} = fadd {ty} 0.0, 0.0  ; conv placeholder")

    def _emit_gemm(self, instr: Instruction) -> None:
        if any(instr.attrs.get(name, 1) != 1 for name in ("alpha", "beta")):
            raise ValueError("Legacy LLVM GEMM does not support nondefault alpha/beta scaling")
        dst = self._dest(instr)
        a = self._op(instr, 0)
        b = self._op(instr, 1)
        ty = self._infer_type(instr)
        self._p(f"  ; gemm: {a} @ {b}")
        self._p(f"  {dst} = fmul {ty} {a}, {b}  ; gemm placeholder")

    def _emit_sigmoid(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)
        if ty == "double":
            self._p(f"  {dst} = call double @exp(double {src})")
            self._p(f"  {dst} = fadd double 1.0, {dst}")
            self._p(f"  {dst} = fdiv double 1.0, {dst}")
        else:
            self._p(f"  {dst} = call float @expf(float {src})")
            self._p(f"  {dst} = fadd float 1.0, {dst}")
            self._p(f"  {dst} = fdiv float 1.0, {dst}")

    def _emit_reshape(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        src = self._op(instr, 0)
        ty = self._infer_type(instr)
        self._p("  ; reshape: passthrough")
        self._p(f"  {dst} = fadd {ty} {src}, 0.0  ; reshape identity")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _infer_type(self, instr: Instruction) -> str:
        if instr.dest is not None:
            return _llvm_type(instr.dest.dtype)
        for op in instr.operands:
            return _llvm_type(op.dtype)
        return "float"

    def _fresh_block(self, hint: str = "block") -> str:
        self._block_counter += 1
        return f"{hint}_{self._block_counter}"


# Module-level helpers --------------------------------------------------------


def _llvm_type(dtype: DataType) -> str:
    return _TYPE_MAP.get(dtype, "float")


def _llvm_const(val: Value) -> str:
    """Format an IR Value as an LLVM constant."""
    if val.const_value is not None:
        cv = val.const_value
        assert isinstance(cv, (float, int))
        return _llvm_const_val(cv, _llvm_type(val.dtype))
    return "0.0"


def _llvm_const_val(value: float | int, ty: str) -> str:
    if ty in ("float", "double"):
        return f"{float(value):e}"
    return str(int(value))
